name: ROS 2 complete CI

# Controls when the workflow will run
on:
  pull_request: # Run on all pull requests
  push:
    branches: [main] # Also run on pushes to the main branch

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          # fetch-depth: 0 is required for the changed-files action to
          # compare the PR against the main branch correctly.
          fetch-depth: 0

      - name: Set up git credentials
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: |
            module_1
            module_2
            # module_3
            # module_4
            # module_5
          target-ros2-distro: jazzy
